import { StyleSheet } from "react-native";

import { colors } from "./colors";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  centeredPanel: {
    alignItems: "center",
    flex: 1,
    gap: 12,
    justifyContent: "center",
    padding: 24,
  },
  loginContent: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 20,
  },
  loginCard: {
    backgroundColor: colors.surface,
    borderColor: "#d9e6de",
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    padding: 20,
    shadowColor: "#0f172a",
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  loginTitle: {
    color: colors.text,
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: 0,
  },
  loginSubtitle: {
    color: colors.textSubtle,
    fontSize: 15,
    lineHeight: 21,
    marginTop: 6,
  },
  loginModeSwitch: {
    backgroundColor: colors.surfaceSoft,
    borderColor: "#cfe4d7",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    marginTop: 16,
    padding: 4,
  },
  loginModeButton: {
    alignItems: "center",
    borderRadius: 8,
    flex: 1,
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  loginModeButtonActive: {
    backgroundColor: colors.primary,
  },
  loginModeButtonText: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0,
  },
  loginModeButtonTextActive: {
    color: colors.surface,
  },
  apiBasePanel: {
    backgroundColor: colors.surfaceSoft,
    borderColor: "#cfe4d7",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 18,
    padding: 12,
  },
  apiBaseLabel: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  apiBaseValue: {
    color: "#334155",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  appHeader: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  appTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: 0,
  },
  headerSubline: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0,
    marginTop: 2,
  },
  sessionPill: {
    backgroundColor: colors.surfaceMuted,
    borderColor: "#d8e4de",
    borderRadius: 8,
    borderWidth: 1,
    maxWidth: "52%",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  sessionPillText: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "700",
  },
  screenContent: {
    padding: 16,
    paddingBottom: 22,
  },
  screenHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    marginBottom: 14,
  },
  screenHeaderText: {
    flex: 1,
  },
  screenTitle: {
    color: colors.text,
    fontSize: 26,
    fontWeight: "800",
    letterSpacing: 0,
  },
  screenSubtitle: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 19,
    marginTop: 3,
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    elevation: 1,
    marginBottom: 14,
    padding: 14,
    shadowColor: "#0f172a",
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  cardHeader: {
    marginBottom: 12,
  },
  cardTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "800",
    letterSpacing: 0,
  },
  cardSubtitle: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 4,
  },
  statCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexBasis: "46%",
    flexGrow: 1,
    marginBottom: 10,
    minHeight: 86,
    padding: 14,
  },
  statValue: {
    color: colors.accent,
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: 0,
  },
  statLabel: {
    color: colors.textSubtle,
    fontSize: 13,
    fontWeight: "700",
    marginTop: 5,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  moduleChip: {
    backgroundColor: colors.chipSurface,
    borderColor: colors.chipBorder,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  moduleChipText: {
    color: colors.chipText,
    fontSize: 13,
    fontWeight: "800",
  },
  fieldLabel: {
    color: "#334155",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 6,
    marginTop: 14,
  },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.borderStrong,
    borderRadius: 8,
    borderWidth: 1,
    color: "#0f172a",
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  multilineInput: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  inlineButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  selectableRow: {
    alignItems: "center",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    marginBottom: 9,
    padding: 12,
  },
  selectableRowSelected: {
    backgroundColor: "#f0fdfa",
    borderColor: colors.primaryBorder,
  },
  rowMain: {
    flex: 1,
  },
  rowTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0,
  },
  rowMeta: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  rowColorDot: {
    borderColor: colors.borderStrong,
    borderRadius: 8,
    borderWidth: 1,
    height: 22,
    width: 22,
  },
  selectionMark: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "800",
  },
  selectionMarkSelected: {
    color: colors.primary,
  },
  reviewItem: {
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    marginBottom: 12,
    paddingBottom: 12,
  },
  itemButtonRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  commentRow: {
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    marginBottom: 10,
    paddingBottom: 10,
  },
  infoRow: {
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    paddingVertical: 9,
  },
  infoLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  infoValue: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "700",
    marginTop: 3,
  },
  loadingRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  mutedText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  notice: {
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  noticeError: {
    backgroundColor: colors.dangerSurface,
    borderColor: colors.dangerBorder,
  },
  noticeSuccess: {
    backgroundColor: colors.successSurface,
    borderColor: colors.successBorder,
  },
  noticeWarning: {
    backgroundColor: colors.warningSurface,
    borderColor: colors.warningBorder,
  },
  noticeInfo: {
    backgroundColor: colors.surfaceSoft,
    borderColor: "#b8d8ca",
  },
  noticeText: {
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  noticeTextError: {
    color: colors.danger,
  },
  noticeTextSuccess: {
    color: colors.successText,
  },
  noticeTextWarning: {
    color: colors.warningText,
  },
  noticeTextInfo: {
    color: colors.primary,
  },
  button: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 8,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  buttonCompact: {
    minHeight: 38,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  buttonSecondary: {
    backgroundColor: colors.surfaceSoft,
    borderColor: "#b8d8ca",
    borderWidth: 1,
  },
  buttonDanger: {
    backgroundColor: colors.danger,
  },
  buttonPressed: {
    opacity: 0.82,
  },
  buttonDisabled: {
    backgroundColor: "#cbd5e1",
    borderColor: "#cbd5e1",
  },
  buttonText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0,
  },
  buttonSecondaryText: {
    color: colors.primary,
  },
  buttonTextDisabled: {
    color: colors.surfaceMuted,
  },
  compactStack: {
    gap: 10,
  },
  splitRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  choiceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  choiceButton: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  choiceButtonSelected: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryBorder,
  },
  choiceButtonText: {
    color: colors.textSubtle,
    fontSize: 13,
    fontWeight: "800",
  },
  choiceButtonTextSelected: {
    color: colors.primary,
  },
  formSection: {
    marginTop: 6,
  },
  divider: {
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    marginVertical: 12,
  },
  swatchRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 12,
  },
  colorSwatch: {
    borderColor: colors.borderStrong,
    borderRadius: 8,
    borderWidth: 1,
    height: 38,
    width: 38,
  },
  colorSwatchSelected: {
    borderColor: colors.text,
    borderWidth: 3,
  },
  calendarWeekRow: {
    flexDirection: "row",
    gap: 4,
    marginTop: 14,
  },
  calendarWeekday: {
    color: colors.textMuted,
    flexBasis: "13.4%",
    flexGrow: 1,
    fontSize: 12,
    fontWeight: "800",
    textAlign: "center",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 6,
  },
  calendarCell: {
    alignItems: "center",
    aspectRatio: 1,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexBasis: "13.4%",
    flexGrow: 1,
    justifyContent: "center",
    minHeight: 42,
    padding: 3,
  },
  calendarCellMuted: {
    backgroundColor: "#f1f5f9",
    opacity: 0.58,
  },
  calendarCellSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  calendarCellText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  calendarCellTextMuted: {
    color: colors.textMuted,
  },
  calendarCellTextSelected: {
    color: colors.surface,
  },
  calendarSubjectRow: {
    flexDirection: "row",
    gap: 2,
    marginTop: 3,
  },
  calendarSubjectInitial: {
    color: colors.primary,
    fontSize: 9,
    fontWeight: "900",
  },
  calendarSubjectInitialSelected: {
    color: colors.surface,
  },
  dangerText: {
    color: colors.danger,
  },
});
