from __future__ import annotations

from copy import deepcopy
from typing import Any


BuiltInCourse = dict[str, Any]


_MATH_COURSES: list[BuiltInCourse] = [
    {
        "grade_level": 1,
        "title": "Grade 1 Math Foundations",
        "description": "A hands-on first grade path for number sense, addition, subtraction, shapes, measurement, and early data reading.",
        "color": "#20d3ff",
        "icon": "abacus",
        "topics": [
            "counting to 120",
            "place value",
            "addition and subtraction within 20",
            "measurement",
            "shapes",
            "picture graphs",
        ],
        "lessons": [
            {
                "sequence_order": 1,
                "title": "Counting Forward and Backward to 120",
                "overview": "Students count by ones and tens, read numbers to 120, and locate missing numbers in a sequence.",
                "estimated_minutes": 25,
                "activity_prompt": "Build a 120 chart. Cover five numbers and ask the student to name each hidden number using counting patterns.",
                "answer_key": "Look for accurate counting by ones and tens, especially across decade changes such as 39 to 40.",
            },
            {
                "sequence_order": 2,
                "title": "Tens and Ones Place Value",
                "overview": "Students model two-digit numbers as groups of tens and leftover ones.",
                "estimated_minutes": 30,
                "activity_prompt": "Use sticks, cubes, or drawings to show 47, 62, and 89 as tens and ones.",
                "answer_key": "47 = 4 tens and 7 ones; 62 = 6 tens and 2 ones; 89 = 8 tens and 9 ones.",
            },
            {
                "sequence_order": 3,
                "title": "Addition Within 20",
                "overview": "Students practice counting on, making ten, and using doubles to add within 20.",
                "estimated_minutes": 25,
                "activity_prompt": "Solve 8 + 5, 6 + 6, and 9 + 4. Ask the student to explain the strategy used.",
                "answer_key": "8 + 5 = 13; 6 + 6 = 12; 9 + 4 = 13. Strong explanations mention making ten or doubles.",
            },
            {
                "sequence_order": 4,
                "title": "Subtraction Within 20",
                "overview": "Students subtract using take-away, counting back, and related addition facts.",
                "estimated_minutes": 25,
                "activity_prompt": "Act out 15 - 6, 13 - 4, and 17 - 9 with counters, then write equations.",
                "answer_key": "15 - 6 = 9; 13 - 4 = 9; 17 - 9 = 8.",
            },
            {
                "sequence_order": 5,
                "title": "Comparing and Ordering Numbers",
                "overview": "Students compare two-digit numbers using tens, ones, and comparison symbols.",
                "estimated_minutes": 20,
                "activity_prompt": "Order 34, 43, 39, and 30 from least to greatest. Compare 58 and 85 with a symbol.",
                "answer_key": "30, 34, 39, 43. 58 < 85 because 5 tens is less than 8 tens.",
            },
            {
                "sequence_order": 6,
                "title": "Measuring Length With Objects",
                "overview": "Students measure by lining up equal-size objects without gaps or overlaps.",
                "estimated_minutes": 25,
                "activity_prompt": "Measure a book, spoon, and pencil with paper clips. Record and compare the lengths.",
                "answer_key": "Check that the student starts at one end, uses equal units, and compares results with correct language.",
            },
            {
                "sequence_order": 7,
                "title": "Two-Dimensional and Three-Dimensional Shapes",
                "overview": "Students identify circles, triangles, rectangles, cubes, cones, cylinders, and spheres.",
                "estimated_minutes": 30,
                "activity_prompt": "Sort household objects into shape groups and describe sides, corners, faces, or curved surfaces.",
                "answer_key": "Descriptions should use observable attributes such as sides, vertices, flat faces, and curved surfaces.",
            },
            {
                "sequence_order": 8,
                "title": "Picture Graphs and Simple Questions",
                "overview": "Students collect category data, make a picture graph, and answer more/less questions.",
                "estimated_minutes": 30,
                "activity_prompt": "Graph favorite fruits for family members or toys by color, then ask three comparison questions.",
                "answer_key": "Student should count symbols accurately and answer most, fewest, how many more, and total questions.",
            },
        ],
    },
    {
        "grade_level": 2,
        "title": "Grade 2 Math Foundations",
        "description": "A second grade sequence covering fluency within 100, three-digit place value, money, time, measurement, arrays, and graphs.",
        "color": "#7c83ff",
        "icon": "calculator",
        "topics": [
            "addition and subtraction within 100",
            "three-digit place value",
            "time and money",
            "measurement",
            "arrays",
            "bar graphs",
        ],
        "lessons": [
            {
                "sequence_order": 1,
                "title": "Skip Counting by 2s, 5s, 10s, and 100s",
                "overview": "Students use skip counting as a bridge to money, place value, and multiplication readiness.",
                "estimated_minutes": 25,
                "activity_prompt": "Create number chains from 0 to 120 by 2s, 5s, and 10s, then from 100 to 900 by 100s.",
                "answer_key": "Listen for steady patterns and correct transitions such as 95, 100, 105.",
            },
            {
                "sequence_order": 2,
                "title": "Hundreds, Tens, and Ones",
                "overview": "Students read and build three-digit numbers using hundreds, tens, and ones.",
                "estimated_minutes": 30,
                "activity_prompt": "Model 248, 305, and 470 with drawings or place-value blocks.",
                "answer_key": "248 = 2 hundreds, 4 tens, 8 ones; 305 = 3 hundreds, 0 tens, 5 ones; 470 = 4 hundreds, 7 tens, 0 ones.",
            },
            {
                "sequence_order": 3,
                "title": "Add Within 100 With Strategies",
                "overview": "Students add two-digit numbers with open number lines, tens-and-ones, and compensation.",
                "estimated_minutes": 30,
                "activity_prompt": "Solve 37 + 28 and 46 + 35 in two different ways.",
                "answer_key": "37 + 28 = 65; 46 + 35 = 81. Strategies should preserve place value.",
            },
            {
                "sequence_order": 4,
                "title": "Subtract Within 100 With Strategies",
                "overview": "Students subtract two-digit numbers by decomposing tens and ones or counting up.",
                "estimated_minutes": 30,
                "activity_prompt": "Solve 72 - 38 and 64 - 27. Ask which strategy felt clearest.",
                "answer_key": "72 - 38 = 34; 64 - 27 = 37.",
            },
            {
                "sequence_order": 5,
                "title": "Time to the Nearest Five Minutes",
                "overview": "Students read analog and digital clocks to the nearest five minutes.",
                "estimated_minutes": 25,
                "activity_prompt": "Draw clocks for 2:15, 6:40, and 9:05, then read three clocks around the house.",
                "answer_key": "Minute hand positions: 15 at 3, 40 at 8, 05 at 1.",
            },
            {
                "sequence_order": 6,
                "title": "Money With Coins and Dollars",
                "overview": "Students count mixed coin values and connect skip counting to nickels, dimes, quarters, and dollars.",
                "estimated_minutes": 30,
                "activity_prompt": "Make 68 cents three ways using pennies, nickels, dimes, and quarters.",
                "answer_key": "Accept any valid combinations totaling 68 cents, such as 2 quarters, 1 dime, 1 nickel, 3 pennies.",
            },
            {
                "sequence_order": 7,
                "title": "Arrays and Equal Groups",
                "overview": "Students represent repeated addition with rows and columns.",
                "estimated_minutes": 25,
                "activity_prompt": "Build arrays for 3 + 3 + 3 + 3 and 5 + 5 + 5. Write repeated addition equations.",
                "answer_key": "Four groups of 3 = 12; three groups of 5 = 15.",
            },
            {
                "sequence_order": 8,
                "title": "Bar Graphs and Measurement Data",
                "overview": "Students collect measurements, organize them, and answer questions from a bar graph.",
                "estimated_minutes": 35,
                "activity_prompt": "Measure five objects to the nearest inch and make a bar graph of their lengths.",
                "answer_key": "Graph should have labels, consistent scale, and accurate answers to comparison questions.",
            },
        ],
    },
    {
        "grade_level": 3,
        "title": "Grade 3 Math Foundations",
        "description": "A third grade course for multiplication, division, fractions, area, perimeter, elapsed time, geometry, and data.",
        "color": "#ff4f9e",
        "icon": "times",
        "topics": [
            "multiplication facts",
            "division",
            "fractions",
            "area and perimeter",
            "elapsed time",
            "line plots",
        ],
        "lessons": [
            {
                "sequence_order": 1,
                "title": "Multiplication as Equal Groups",
                "overview": "Students connect equal groups, arrays, skip counting, and multiplication equations.",
                "estimated_minutes": 30,
                "activity_prompt": "Model 4 x 6, 7 x 3, and 5 x 8 with arrays and repeated addition.",
                "answer_key": "4 x 6 = 24; 7 x 3 = 21; 5 x 8 = 40.",
            },
            {
                "sequence_order": 2,
                "title": "Division as Sharing and Grouping",
                "overview": "Students interpret division as fair shares and as how many groups.",
                "estimated_minutes": 30,
                "activity_prompt": "Use 24 counters to solve 24 / 4 and 24 / 6. Explain both stories.",
                "answer_key": "24 / 4 = 6; 24 / 6 = 4.",
            },
            {
                "sequence_order": 3,
                "title": "Fact Families and Unknowns",
                "overview": "Students use related multiplication and division facts to find unknown factors.",
                "estimated_minutes": 25,
                "activity_prompt": "Complete 6 x ? = 42, ? x 8 = 56, and 45 / ? = 5.",
                "answer_key": "7, 7, and 9.",
            },
            {
                "sequence_order": 4,
                "title": "Fractions on a Number Line",
                "overview": "Students partition number lines and place unit fractions and non-unit fractions.",
                "estimated_minutes": 30,
                "activity_prompt": "Draw number lines from 0 to 1 for halves, thirds, fourths, and sixths. Mark 2/3 and 5/6.",
                "answer_key": "Segments must be equal. 2/3 is the second third; 5/6 is the fifth sixth.",
            },
            {
                "sequence_order": 5,
                "title": "Equivalent Fractions With Models",
                "overview": "Students use fraction strips and area models to name equivalent fractions.",
                "estimated_minutes": 35,
                "activity_prompt": "Show why 1/2 = 2/4 and 3/6. Find one fraction equivalent to 2/3.",
                "answer_key": "Equivalent answers for 2/3 include 4/6 or 6/9 when models use equal parts.",
            },
            {
                "sequence_order": 6,
                "title": "Area and Perimeter",
                "overview": "Students distinguish area from perimeter and solve rectangle problems.",
                "estimated_minutes": 30,
                "activity_prompt": "Find the area and perimeter of rectangles that are 4 by 7 and 6 by 6.",
                "answer_key": "4 by 7: area 28 square units, perimeter 22 units. 6 by 6: area 36, perimeter 24.",
            },
            {
                "sequence_order": 7,
                "title": "Elapsed Time Problems",
                "overview": "Students solve elapsed time on clocks and timelines.",
                "estimated_minutes": 30,
                "activity_prompt": "A lesson starts at 9:35 and ends at 10:20. A game starts at 2:15 and lasts 50 minutes. Solve both.",
                "answer_key": "9:35 to 10:20 is 45 minutes. 2:15 plus 50 minutes is 3:05.",
            },
            {
                "sequence_order": 8,
                "title": "Line Plots With Fractions",
                "overview": "Students create and read line plots using halves and fourths.",
                "estimated_minutes": 35,
                "activity_prompt": "Measure six pencils to the nearest quarter inch and place the values on a line plot.",
                "answer_key": "Check equal spacing, clear labels, and correct counts for repeated measurements.",
            },
        ],
    },
    {
        "grade_level": 4,
        "title": "Grade 4 Math Foundations",
        "description": "A fourth grade course for multi-digit operations, factors, fraction operations, decimals, angles, measurement, and data.",
        "color": "#38d98e",
        "icon": "ruler",
        "topics": [
            "multi-digit multiplication",
            "division with remainders",
            "factors and multiples",
            "fraction operations",
            "decimals",
            "angles",
        ],
        "lessons": [
            {
                "sequence_order": 1,
                "title": "Place Value to One Million",
                "overview": "Students read, write, compare, and round whole numbers through one million.",
                "estimated_minutes": 30,
                "activity_prompt": "Write 482,619 in expanded form, round it to the nearest thousand, and compare it to 428,916.",
                "answer_key": "400,000 + 80,000 + 2,000 + 600 + 10 + 9; rounds to 483,000; 482,619 > 428,916.",
            },
            {
                "sequence_order": 2,
                "title": "Multi-Digit Multiplication",
                "overview": "Students multiply using area models, partial products, and the standard algorithm.",
                "estimated_minutes": 35,
                "activity_prompt": "Solve 34 x 27 and 126 x 4 using an area model or partial products.",
                "answer_key": "34 x 27 = 918; 126 x 4 = 504.",
            },
            {
                "sequence_order": 3,
                "title": "Division With Remainders",
                "overview": "Students divide multi-digit numbers and interpret remainders in context.",
                "estimated_minutes": 35,
                "activity_prompt": "Solve 157 / 6 and 248 / 5. Write a sentence explaining each remainder.",
                "answer_key": "157 / 6 = 26 R1; 248 / 5 = 49 R3.",
            },
            {
                "sequence_order": 4,
                "title": "Factors, Multiples, Prime, and Composite",
                "overview": "Students list factors and multiples and classify numbers as prime or composite.",
                "estimated_minutes": 30,
                "activity_prompt": "List factor pairs for 36, first five multiples of 8, and decide whether 29 and 39 are prime.",
                "answer_key": "36 factors include 1x36, 2x18, 3x12, 4x9, 6x6. Multiples: 8, 16, 24, 32, 40. 29 prime, 39 composite.",
            },
            {
                "sequence_order": 5,
                "title": "Adding and Subtracting Fractions",
                "overview": "Students add and subtract fractions with like denominators and decompose mixed numbers.",
                "estimated_minutes": 35,
                "activity_prompt": "Solve 3/8 + 4/8, 7/10 - 2/10, and 1 2/5 + 3/5.",
                "answer_key": "7/8; 5/10 or 1/2; 2.",
            },
            {
                "sequence_order": 6,
                "title": "Decimals and Fraction Connections",
                "overview": "Students connect tenths and hundredths to decimal notation and compare decimals.",
                "estimated_minutes": 30,
                "activity_prompt": "Write 7/10 and 43/100 as decimals. Compare 0.6 and 0.58.",
                "answer_key": "7/10 = 0.7; 43/100 = 0.43; 0.6 > 0.58.",
            },
            {
                "sequence_order": 7,
                "title": "Angles and Lines",
                "overview": "Students identify angle types, measure angles, and recognize parallel and perpendicular lines.",
                "estimated_minutes": 35,
                "activity_prompt": "Draw acute, right, obtuse, and straight angles. Find two parallel and two perpendicular examples at home.",
                "answer_key": "Check angle category accuracy and correct use of parallel/perpendicular language.",
            },
            {
                "sequence_order": 8,
                "title": "Measurement Conversion and Data",
                "overview": "Students convert within one measurement system and solve word problems with data tables.",
                "estimated_minutes": 35,
                "activity_prompt": "Convert 3 feet to inches, 5 yards to feet, and 2 liters to milliliters. Make a table for daily reading minutes.",
                "answer_key": "36 inches; 15 feet; 2000 milliliters. Data table should be organized and readable.",
            },
        ],
    },
    {
        "grade_level": 5,
        "title": "Grade 5 Math Foundations",
        "description": "A fifth grade course for decimal operations, fraction operations, volume, coordinate planes, expressions, and multi-step problems.",
        "color": "#ffb020",
        "icon": "function",
        "topics": [
            "decimal operations",
            "fraction multiplication and division",
            "volume",
            "coordinate planes",
            "numerical expressions",
            "multi-step word problems",
        ],
        "lessons": [
            {
                "sequence_order": 1,
                "title": "Place Value With Decimals",
                "overview": "Students read, write, compare, and round decimals to thousandths.",
                "estimated_minutes": 30,
                "activity_prompt": "Compare 4.507 and 4.57. Round 12.386 to the nearest tenth and hundredth.",
                "answer_key": "4.507 < 4.57. 12.386 rounds to 12.4 and 12.39.",
            },
            {
                "sequence_order": 2,
                "title": "Add and Subtract Decimals",
                "overview": "Students line up place values to add and subtract decimals in money and measurement contexts.",
                "estimated_minutes": 30,
                "activity_prompt": "Solve 18.75 + 6.8 and 24.3 - 9.86. Explain why the decimal points align.",
                "answer_key": "25.55 and 14.44. Decimal points align to keep tenths with tenths and hundredths with hundredths.",
            },
            {
                "sequence_order": 3,
                "title": "Multiply Decimals",
                "overview": "Students use area models and place-value reasoning to multiply decimals.",
                "estimated_minutes": 35,
                "activity_prompt": "Solve 3.4 x 6 and 2.5 x 1.2 using an estimate first.",
                "answer_key": "3.4 x 6 = 20.4; 2.5 x 1.2 = 3.0. Estimates should be close to the final values.",
            },
            {
                "sequence_order": 4,
                "title": "Divide Decimals by Whole Numbers",
                "overview": "Students divide decimals by whole numbers and interpret quotients in context.",
                "estimated_minutes": 35,
                "activity_prompt": "Divide $18.75 equally among 3 people and 7.2 meters into 4 equal pieces.",
                "answer_key": "$6.25 and 1.8 meters.",
            },
            {
                "sequence_order": 5,
                "title": "Add and Subtract Fractions With Unlike Denominators",
                "overview": "Students find common denominators and solve fraction addition and subtraction problems.",
                "estimated_minutes": 35,
                "activity_prompt": "Solve 1/3 + 1/4, 5/6 - 1/2, and 2 1/5 + 1 3/10.",
                "answer_key": "7/12; 1/3; 3 1/2.",
            },
            {
                "sequence_order": 6,
                "title": "Multiply Fractions and Mixed Numbers",
                "overview": "Students interpret fraction multiplication as scaling and area.",
                "estimated_minutes": 35,
                "activity_prompt": "Solve 2/3 x 9, 3/4 x 2/5, and 1 1/2 x 4.",
                "answer_key": "6; 3/10; 6.",
            },
            {
                "sequence_order": 7,
                "title": "Volume of Rectangular Prisms",
                "overview": "Students find volume with unit cubes and the formula length x width x height.",
                "estimated_minutes": 35,
                "activity_prompt": "Find the volume of boxes measuring 3 x 4 x 5 and 8 x 2 x 6.",
                "answer_key": "60 cubic units and 96 cubic units.",
            },
            {
                "sequence_order": 8,
                "title": "Coordinate Plane and Patterns",
                "overview": "Students graph ordered pairs in the first quadrant and analyze numerical patterns.",
                "estimated_minutes": 35,
                "activity_prompt": "Plot (1,2), (2,4), (3,6), and (4,8). Describe the pattern and write the next point.",
                "answer_key": "The y-value is double the x-value. Next point is (5,10).",
            },
        ],
    },
]


def list_builtin_math_courses() -> list[BuiltInCourse]:
    return deepcopy(_MATH_COURSES)


def get_builtin_math_course(grade_level: int) -> BuiltInCourse | None:
    for course in _MATH_COURSES:
        if course["grade_level"] == grade_level:
            return deepcopy(course)
    return None
