from __future__ import annotations

from copy import deepcopy
from typing import Any


BuiltInCourse = dict[str, Any]


def _lesson(
    *,
    sequence_order: int,
    title: str,
    overview: str,
    objective: str,
    model: str,
    guided: str,
    independent: str,
    assessment: str,
    answer_key: str,
    materials: str,
    extension: str,
    remediation: str,
    estimated_minutes: int = 45,
) -> dict[str, Any]:
    return {
        "sequence_order": sequence_order,
        "title": title,
        "overview": overview,
        "estimated_minutes": estimated_minutes,
        "activity_prompt": "\n".join(
            [
                f"Teacher model: {model}",
                f"Guided practice: {guided}",
                f"Independent practice: {independent}",
                f"Exit ticket: {assessment}",
            ]
        ),
        "answer_key": answer_key,
        "learning_objectives": "\n".join(
            [
                f"- {objective}",
                "- Explain the strategy in words, drawings, or equations.",
                "- Check the answer with a second representation.",
            ]
        ),
        "materials": materials,
        "warm_up": (
            "Start with a 5 minute review of prerequisite facts or vocabulary. "
            "Have the student solve two quick examples aloud and explain the first step before moving into the lesson."
        ),
        "direct_instruction": model,
        "guided_practice": guided,
        "independent_practice": independent,
        "assessment": assessment,
        "extension": extension,
        "remediation": remediation,
    }


def _grade_1_lessons() -> list[dict[str, Any]]:
    specs = [
        (
            "Counting Forward and Backward to 120",
            "Read, write, and count numbers to 120 from any starting point.",
            "Build a 120 chart, circle decade numbers, and show how 39 becomes 40 and 99 becomes 100.",
            "Fill missing numbers in 18, 19, __, 21; 47, __, 49; and 108, 109, __.",
            "Complete a mixed 120-chart strip with 12 missing numbers and read the finished strip aloud.",
            "Name the missing numbers: 56, __, 58, 59, __.",
            "57 and 60. Listen for accurate decade transitions.",
        ),
        (
            "Tens and Ones Place Value",
            "Represent two-digit numbers as tens and ones.",
            "Bundle craft sticks into tens and leave single sticks as ones. Model 47 as 4 tens and 7 ones.",
            "Build 32, 58, and 70 with bundles, drawings, and expanded form.",
            "Write tens/ones and expanded form for 26, 41, 63, 85, and 90.",
            "Show 74 with tens and ones and write 70 + 4.",
            "74 = 7 tens and 4 ones = 70 + 4.",
        ),
        (
            "Comparing and Ordering Numbers",
            "Compare two-digit numbers using tens, ones, and symbols.",
            "Compare 58 and 85 by looking at tens first, then compare 64 and 69 by looking at ones.",
            "Place 34, 43, 39, and 30 on a number line and order them least to greatest.",
            "Compare 27 and 72, 61 and 59, 88 and 83; then order 45, 54, 40, 49.",
            "Fill in: 73 __ 37 and explain why.",
            "73 > 37 because 7 tens is more than 3 tens.",
        ),
        (
            "Addition Within 20: Counting On",
            "Add within 20 by counting on from the larger addend.",
            "Model 8 + 5 by holding 8 in mind and counting 9, 10, 11, 12, 13 on fingers.",
            "Solve 9 + 4, 7 + 6, and 12 + 3 with the counting-on strategy.",
            "Solve 6 + 5, 8 + 7, 4 + 9, 11 + 6, and 13 + 5. Circle the larger addend first.",
            "Solve 9 + 6 and describe the count-on steps.",
            "9 + 6 = 15.",
        ),
        (
            "Addition Within 20: Make Ten",
            "Use ten as a friendly number to add within 20.",
            "Break 7 into 2 and 5 so 8 + 7 becomes 8 + 2 + 5 = 15.",
            "Use ten frames for 9 + 5, 6 + 8, and 7 + 7.",
            "Solve 8 + 6, 9 + 4, 7 + 5, 6 + 7, and 5 + 9 with make-ten drawings.",
            "Show how to make ten for 8 + 5.",
            "8 + 5 = 13 by moving 2 from 5 to make 10, with 3 left.",
        ),
        (
            "Subtraction Within 20",
            "Subtract within 20 using take-away, count-back, and related addition.",
            "Use counters to act out 15 - 6, then check with 6 + 9 = 15.",
            "Solve 13 - 4, 17 - 9, and 16 - 7 with counters and related facts.",
            "Solve 12 - 5, 18 - 8, 14 - 6, 19 - 7, and 11 - 3.",
            "Solve 16 - 9 and write the related addition fact.",
            "16 - 9 = 7; related fact: 9 + 7 = 16.",
        ),
        (
            "Addition and Subtraction Word Problems",
            "Represent change, put-together, and compare word problems.",
            "Read a story, underline the question, draw the action, and write an equation with a box for the unknown.",
            "Solve: Mia had 8 shells and found 5 more. Ben had 14 stickers and gave away 6.",
            "Solve five mixed stories and label each equation with the answer unit.",
            "A jar has 9 red buttons and 7 blue buttons. How many buttons?",
            "9 + 7 = 16 buttons.",
        ),
        (
            "Length With Nonstandard Units",
            "Measure length using equal-size units without gaps or overlaps.",
            "Line up paper clips end to end along a pencil and discuss why gaps change the count.",
            "Measure a book, spoon, and crayon with cubes; compare longest and shortest.",
            "Measure four household objects, record lengths, and order them shortest to longest.",
            "Explain why all units must be the same size.",
            "Equal units make the measurement fair and repeatable.",
        ),
        (
            "Time to the Hour and Half Hour",
            "Read analog and digital clocks to the hour and half hour.",
            "Show how the minute hand points to 12 for o'clock and 6 for half past; move the hour hand halfway.",
            "Build clocks for 3:00, 7:30, and 11:30 with a paper clock.",
            "Draw hands for 1:00, 4:30, 9:00, 12:30, and 6:00.",
            "Draw 8:30 and explain both hands.",
            "Minute hand on 6; hour hand halfway between 8 and 9.",
        ),
        (
            "Two-Dimensional and Three-Dimensional Shapes",
            "Identify and describe shapes by sides, vertices, faces, and curved surfaces.",
            "Sort cards into triangles, rectangles, circles, cubes, cylinders, cones, and spheres using attributes.",
            "Find five household objects and name their 2D or 3D shape attributes.",
            "Draw or list examples of each shape and write one attribute for each.",
            "Name a shape with 4 sides and 4 vertices.",
            "Rectangle or square; accept either with correct attributes.",
        ),
        (
            "Partitioning Shapes Into Equal Shares",
            "Partition circles and rectangles into halves and fourths.",
            "Fold paper rectangles into two equal parts, then four equal parts, and compare equal vs unequal shares.",
            "Shade one half, two fourths, and three fourths on prepared shapes.",
            "Partition six shapes; label halves, fourths, whole, and equal shares.",
            "If a rectangle is split into 4 equal parts and 1 is shaded, what is shaded?",
            "One fourth, or 1/4.",
        ),
        (
            "Picture Graphs and Data Questions",
            "Collect category data, make a picture graph, and answer more/less questions.",
            "Survey family favorite fruits and create a picture graph with one picture per vote.",
            "Ask: Which has the most? Which has the fewest? How many more apples than bananas?",
            "Make a new graph for toy colors and write three comparison answers.",
            "If red has 6 and blue has 4, how many more red?",
            "2 more red items.",
        ),
    ]
    return _build_lessons(specs, "counters, ten frames, number cards, paper clock, graph paper, pencils")


def _grade_2_lessons() -> list[dict[str, Any]]:
    specs = [
        (
            "Skip Counting by 2s, 5s, 10s, and 100s",
            "Skip count fluently and connect patterns to money and place value.",
            "Use a hundred chart to color multiples of 2, 5, and 10; then count 100, 200, 300 to 900.",
            "Continue patterns from 35 by 5s, 48 by 2s, and 120 by 10s.",
            "Write four skip-counting chains and identify the rule for each chain.",
            "Continue 75, 80, 85, __, __.",
            "90, 95.",
        ),
        (
            "Hundreds, Tens, and Ones",
            "Read, build, and write three-digit numbers.",
            "Model 248, 305, and 470 with base-ten drawings and expanded form.",
            "Trade 10 ones for 1 ten and 10 tens for 1 hundred using drawings.",
            "Write standard, expanded, and word form for 126, 409, 580, and 731.",
            "Write 604 in expanded form.",
            "600 + 4, or 600 + 0 + 4.",
        ),
        (
            "Compare Three-Digit Numbers",
            "Compare numbers to 1000 using place value.",
            "Line up hundreds, tens, and ones for 527 and 572. Compare hundreds first, then tens.",
            "Use >, <, or = for 318 and 381; 640 and 604; 909 and 909.",
            "Order 404, 440, 414, 441, and 410 from least to greatest.",
            "Compare 725 __ 752.",
            "725 < 752 because 2 tens is less than 5 tens.",
        ),
        (
            "Add Within 100 With Strategies",
            "Add two-digit numbers using place value, compensation, and open number lines.",
            "Solve 37 + 28 by adding tens and ones, then check with an open number line.",
            "Solve 46 + 35 and 29 + 54 in two different ways.",
            "Solve 58 + 27, 34 + 49, 66 + 18, and 75 + 16; label regrouping.",
            "Solve 67 + 25.",
            "92.",
        ),
        (
            "Subtract Within 100 With Strategies",
            "Subtract two-digit numbers using decomposition and counting up.",
            "Model 72 - 38 by decomposing 72 into 60 + 12, then subtracting 30 and 8.",
            "Solve 64 - 27 and 83 - 45 with drawings or number lines.",
            "Solve 91 - 36, 70 - 28, 55 - 19, and 42 - 17.",
            "Solve 80 - 46.",
            "34.",
        ),
        (
            "Add and Subtract Within 1000",
            "Use hundreds, tens, and ones to add and subtract three-digit numbers.",
            "Add 356 + 278 with place-value blocks and show regrouping ones and tens.",
            "Solve 524 + 189, 703 - 248, and 600 - 375 step by step.",
            "Complete six mixed problems and write one check using inverse operations.",
            "Solve 431 + 286.",
            "717.",
        ),
        (
            "Word Problems With Unknowns",
            "Solve one- and two-step word problems with unknowns in any position.",
            "Model a start-change-result story with a bar diagram before writing the equation.",
            "Solve: A library had 235 books, bought 148, then lent out 97. How many remain?",
            "Solve four word problems; underline givens and box the question.",
            "Sam has 46 cards. He needs 80. How many more?",
            "34 more cards.",
        ),
        (
            "Money With Coins and Dollars",
            "Count mixed coins and dollars and make equivalent amounts.",
            "Review penny, nickel, dime, quarter, and dollar values with skip counting.",
            "Make 68 cents three ways; then count $3.47 using bills and coins.",
            "Solve eight money counts and two make-this-amount challenges.",
            "How much is 2 quarters, 1 dime, 1 nickel, and 3 pennies?",
            "68 cents.",
        ),
        (
            "Time to the Nearest Five Minutes",
            "Read and write time to the nearest five minutes using analog and digital clocks.",
            "Connect each number on a clock to five-minute counts around the circle.",
            "Draw 2:15, 6:40, 9:05, and 11:55; explain hour-hand placement.",
            "Match 10 analog clocks to digital times and write two time stories.",
            "Where is the minute hand at 3:25?",
            "On the 5.",
        ),
        (
            "Length and Measurement Tools",
            "Measure and estimate length using inches, feet, centimeters, and meters.",
            "Compare an inch ruler and centimeter ruler; show why the same object has different counts.",
            "Measure five objects twice, once in inches and once in centimeters.",
            "Estimate and measure room objects; calculate the difference between estimate and actual.",
            "Which is better for a pencil: centimeters or meters?",
            "Centimeters.",
        ),
        (
            "Arrays, Repeated Addition, and Even/Odd",
            "Use arrays and repeated addition as preparation for multiplication.",
            "Build 4 rows of 3 counters and write 3 + 3 + 3 + 3 = 12.",
            "Create arrays for 5 + 5 + 5 and 2 + 2 + 2 + 2 + 2; decide if totals are even or odd.",
            "Draw six arrays, write repeated addition, and label even or odd totals.",
            "Is 17 even or odd? Explain.",
            "Odd because it cannot be split into two equal groups.",
        ),
        (
            "Bar Graphs and Line Plots",
            "Represent measurement and category data with graphs.",
            "Collect shoe sizes or object lengths, then build a bar graph and a line plot.",
            "Answer comparison questions using graph titles, labels, and scale.",
            "Create a graph from a small data table and write five questions someone can answer.",
            "If Monday has 7 and Tuesday has 4, how many more Monday?",
            "3 more.",
        ),
    ]
    return _build_lessons(specs, "base-ten blocks or drawings, hundred chart, coins, ruler, paper clock, graph paper")


def _grade_3_lessons() -> list[dict[str, Any]]:
    specs = [
        (
            "Multiplication as Equal Groups",
            "Connect equal groups, arrays, skip counting, and multiplication equations.",
            "Model 4 groups of 6 with counters, draw a 4 by 6 array, and write 4 x 6 = 24.",
            "Build 7 x 3, 5 x 8, and 6 x 4 with arrays and repeated addition.",
            "Solve and draw arrays for 3 x 9, 8 x 4, 2 x 7, 6 x 6, and 10 x 5.",
            "Represent 5 x 7 two ways.",
            "5 x 7 = 35; accept equal groups, repeated addition, or array.",
        ),
        (
            "Division as Sharing and Grouping",
            "Interpret division as fair sharing and equal-size grouping.",
            "Use 24 counters to show 24 / 4 as four fair shares and 24 / 6 as groups of six.",
            "Solve 18 / 3, 20 / 5, and 32 / 8 with drawings and equations.",
            "Write a division story for each: 27 / 3, 36 / 6, 40 / 5, and 16 / 4.",
            "Explain the difference between sharing and grouping for 12 / 3.",
            "Sharing: 3 groups get 4 each. Grouping: groups of 3 make 4 groups.",
        ),
        (
            "Fact Families and Unknown Factors",
            "Use related multiplication and division facts to solve unknowns.",
            "Show the fact family for 6, 7, and 42: 6 x 7, 7 x 6, 42 / 6, 42 / 7.",
            "Complete 6 x ? = 42, ? x 8 = 56, and 45 / ? = 5.",
            "Complete ten unknown-factor equations and write the matching division facts.",
            "Solve ? x 9 = 63 and 72 / ? = 8.",
            "7 and 9.",
        ),
        (
            "Properties of Multiplication",
            "Use commutative, associative, and distributive properties to multiply.",
            "Break 7 x 8 into 7 x 5 plus 7 x 3; show that 7 x 8 = 8 x 7.",
            "Use arrays to split 6 x 9, 4 x 12, and 8 x 7 into easier facts.",
            "Solve six facts using a written property strategy, not counting by ones.",
            "Use the distributive property for 9 x 6.",
            "Example: 9 x 6 = 9 x 5 + 9 x 1 = 45 + 9 = 54.",
        ),
        (
            "Two-Step Word Problems",
            "Solve two-step word problems with all four operations.",
            "Use a strip diagram for: 4 bags have 6 apples each, then 9 are eaten.",
            "Solve three stories and write one equation with parentheses for each.",
            "Complete four two-step problems and check whether the answer is reasonable.",
            "3 boxes hold 8 books each. 5 more books are added. How many books?",
            "3 x 8 + 5 = 29 books.",
        ),
        (
            "Fractions as Equal Parts",
            "Name unit fractions and non-unit fractions as equal parts of a whole.",
            "Partition rectangles into halves, thirds, fourths, sixths, and eighths; label each part.",
            "Shade 1/3, 3/4, 5/6, and 2/8 and explain numerator and denominator.",
            "Draw six fractions and write a sentence describing the size of one part.",
            "What does the denominator in 3/5 tell you?",
            "The whole is split into 5 equal parts.",
        ),
        (
            "Fractions on a Number Line",
            "Place unit and non-unit fractions on a number line.",
            "Partition 0 to 1 into thirds and sixths. Mark 2/3 and 5/6.",
            "Place 1/2, 3/4, 4/6, and 1 whole on number lines.",
            "Complete four number lines and explain why spacing must be equal.",
            "Where is 3/4 on a fourths number line?",
            "At the third tick after 0 when 0 to 1 is split into 4 equal parts.",
        ),
        (
            "Equivalent Fractions",
            "Recognize and generate simple equivalent fractions.",
            "Fold one strip into halves and another into fourths; show 1/2 = 2/4.",
            "Use models for 2/3 = 4/6 and 3/4 = 6/8.",
            "Match equivalent fraction cards and justify three matches with drawings.",
            "Name an equivalent fraction for 2/4.",
            "1/2; also accept 4/8 with correct reasoning.",
        ),
        (
            "Area With Unit Squares",
            "Find area by tiling and by multiplying side lengths.",
            "Tile a 4 by 6 rectangle and connect 24 unit squares to 4 x 6.",
            "Find areas of rectangles sized 3 by 8, 5 by 5, and 7 by 4.",
            "Draw four rectangles on grid paper, label sides, and calculate area.",
            "What is the area of a 9 by 3 rectangle?",
            "27 square units.",
        ),
        (
            "Perimeter and Missing Sides",
            "Find perimeter and solve for missing side lengths.",
            "Walk around a rectangle drawing and add all side lengths; compare perimeter to area.",
            "Find perimeters of 6 by 4 and 9 by 2 rectangles; solve a missing side example.",
            "Solve six perimeter problems, including two with a missing side.",
            "A rectangle has sides 8, 8, 5, and 5. What is its perimeter?",
            "26 units.",
        ),
        (
            "Elapsed Time to the Minute",
            "Solve elapsed time problems using clocks and number lines.",
            "Count from 2:15 to 3:00, then to 3:20 on an open number line.",
            "Solve 8:35 to 9:10, 12:05 to 12:47, and 4:20 to 6:00.",
            "Write and solve four elapsed-time stories using start, end, and duration.",
            "How long from 1:45 to 2:30?",
            "45 minutes.",
        ),
        (
            "Line Plots and Measurement Data",
            "Create and interpret line plots with halves and fourths.",
            "Measure pencils to the nearest half inch and place each length on a line plot.",
            "Answer how many, most common, and total measurement questions from the plot.",
            "Build a line plot from a provided data set and answer five questions.",
            "If three objects are 4 1/2 inches, how many X marks at 4 1/2?",
            "Three X marks.",
        ),
    ]
    return _build_lessons(specs, "counters, multiplication chart, fraction strips, grid paper, rulers, paper clocks")


def _grade_4_lessons() -> list[dict[str, Any]]:
    specs = [
        (
            "Place Value to One Million",
            "Read, write, compare, and round multi-digit whole numbers.",
            "Build a place-value chart through millions and show how each place is 10 times the place to its right.",
            "Write 482,619 in expanded form and round 748,392 to the nearest thousand.",
            "Compare and round eight numbers; write three in word form and expanded form.",
            "Round 396,842 to the nearest ten thousand.",
            "400,000.",
        ),
        (
            "Multi-Digit Addition and Subtraction",
            "Add and subtract multi-digit whole numbers accurately.",
            "Use the standard algorithm for 48,276 + 9,845 and explain each regrouping.",
            "Solve 73,004 - 28,659 and check with addition.",
            "Complete ten mixed addition/subtraction problems and verify two with inverse operations.",
            "Solve 506,100 - 278,455.",
            "227,645.",
        ),
        (
            "Multiplication by One-Digit Numbers",
            "Multiply up to four digits by one digit using area models and the standard algorithm.",
            "Model 3 x 2,416 as 3 x 2,000 + 3 x 400 + 3 x 10 + 3 x 6.",
            "Solve 4 x 1,238 and 7 x 3,052 with partial products.",
            "Complete six one-digit multiplication problems and label partial products.",
            "Solve 6 x 4,219.",
            "25,314.",
        ),
        (
            "Two-Digit Multiplication",
            "Multiply two two-digit numbers using area models and partial products.",
            "Break 24 x 36 into 20 x 30, 20 x 6, 4 x 30, and 4 x 6.",
            "Solve 18 x 42 and 35 x 27 with area models.",
            "Complete five two-digit multiplication problems using either area model or algorithm.",
            "Solve 26 x 34.",
            "884.",
        ),
        (
            "Division With Remainders",
            "Divide multi-digit dividends by one-digit divisors and interpret remainders.",
            "Model 157 / 4 with place-value groups and discuss the remainder.",
            "Solve 246 / 3, 319 / 5, and 728 / 6; interpret each remainder in context.",
            "Complete eight division problems and write two remainder story answers.",
            "Solve 95 / 6.",
            "15 remainder 5.",
        ),
        (
            "Factors, Multiples, Prime, and Composite",
            "Identify factors, multiples, prime numbers, and composite numbers.",
            "List factor pairs for 24, then decide whether 29 is prime using divisibility tests.",
            "Find factors for 18, 36, and 49; list multiples of 7 through 70.",
            "Sort numbers 2-50 into prime and composite categories.",
            "Is 51 prime or composite? Explain.",
            "Composite because 3 x 17 = 51.",
        ),
        (
            "Equivalent and Comparing Fractions",
            "Generate equivalent fractions and compare fractions with unlike denominators.",
            "Use fraction strips to compare 3/4 and 5/8; then create common denominators.",
            "Compare 2/3 and 3/5, 5/6 and 7/8, 4/10 and 2/5.",
            "Complete ten comparisons and justify three using models or common denominators.",
            "Compare 3/4 __ 2/3.",
            "3/4 > 2/3.",
        ),
        (
            "Add and Subtract Fractions",
            "Add and subtract fractions and mixed numbers with like denominators.",
            "Model 3/8 + 2/8 and 1 5/6 - 2/6 with fraction strips.",
            "Solve 5/12 + 4/12, 7/10 - 3/10, and 2 3/5 + 1 1/5.",
            "Complete twelve like-denominator fraction problems, simplifying when possible.",
            "Solve 4 7/9 - 2 2/9.",
            "2 5/9.",
        ),
        (
            "Multiply Fractions by Whole Numbers",
            "Interpret a fraction times a whole number as repeated addition.",
            "Show 3 x 2/5 as 2/5 + 2/5 + 2/5 = 6/5 = 1 1/5.",
            "Solve 4 x 3/8, 5 x 1/6, and 7 x 2/3 with models.",
            "Complete ten fraction-by-whole-number problems and convert improper answers.",
            "Solve 6 x 3/4.",
            "18/4 = 4 1/2.",
        ),
        (
            "Decimals and Fraction Equivalents",
            "Read, write, compare, and connect tenths and hundredths to decimals.",
            "Shade 0.3 and 0.47 on grids; write them as 3/10 and 47/100.",
            "Compare 0.6 and 0.58, 0.25 and 0.3, 0.70 and 0.7.",
            "Write ten decimals as fractions and order five decimals from least to greatest.",
            "Which is greater: 0.62 or 0.7?",
            "0.7 because 70 hundredths is greater than 62 hundredths.",
        ),
        (
            "Measurement Conversions",
            "Convert measurements within one system using multiplication and division.",
            "Create a conversion table for inches/feet/yards and cups/pints/quarts/gallons.",
            "Convert 5 ft to inches, 3 yd to feet, 8 cups to quarts, and 4 kg to grams.",
            "Solve ten conversion problems and two word problems involving larger to smaller units.",
            "How many inches are in 7 feet?",
            "84 inches.",
        ),
        (
            "Angles, Lines, and Symmetry",
            "Measure angles and classify lines, rays, angles, and symmetry.",
            "Use a protractor to show 30, 90, 120, and 180 degrees; identify parallel and perpendicular lines.",
            "Measure six angles and draw one acute, right, obtuse, and straight angle.",
            "Complete a geometry sort and draw lines of symmetry for six shapes.",
            "Classify a 135 degree angle.",
            "Obtuse angle.",
        ),
    ]
    return _build_lessons(specs, "place-value chart, grid paper, fraction strips, decimal grids, protractor, ruler")


def _grade_5_lessons() -> list[dict[str, Any]]:
    specs = [
        (
            "Place Value With Decimals to Thousandths",
            "Read, write, compare, and round decimals to thousandths.",
            "Use a place-value chart to show 4.382 and explain tenths, hundredths, and thousandths.",
            "Compare 6.07, 6.7, and 6.007; round 12.486 to tenths and hundredths.",
            "Complete twelve decimal comparisons and rounding tasks.",
            "Round 8.746 to the nearest hundredth.",
            "8.75.",
        ),
        (
            "Powers of Ten and Patterns",
            "Multiply and divide whole numbers and decimals by powers of ten.",
            "Move digits on a place-value chart for 3.4 x 10, 3.4 x 100, and 340 / 10.",
            "Complete patterns for 0.56 x 10, x 100, x 1000 and 7,200 / 10, / 100.",
            "Solve fifteen power-of-ten problems and write the movement rule.",
            "Solve 45.8 x 100.",
            "4,580.",
        ),
        (
            "Multi-Digit Multiplication Fluency",
            "Multiply multi-digit whole numbers using an efficient algorithm.",
            "Use partial products for 348 x 27 and connect each product to place value.",
            "Solve 624 x 53 and 2,418 x 36, checking estimates first.",
            "Complete eight multi-digit multiplication problems and estimate before calculating.",
            "Solve 735 x 42.",
            "30,870.",
        ),
        (
            "Long Division With Two-Digit Divisors",
            "Divide whole numbers using estimates, partial quotients, and standard division.",
            "Solve 1,248 / 24 by estimating 24 x 50, subtracting, and adjusting.",
            "Solve 2,835 / 35 and 4,512 / 48 with partial quotients.",
            "Complete six long-division problems and check each with multiplication.",
            "Solve 936 / 26.",
            "36.",
        ),
        (
            "Add and Subtract Fractions With Unlike Denominators",
            "Use equivalent fractions to add and subtract unlike denominators.",
            "Model 1/2 + 1/3 with sixths, then solve with common denominators.",
            "Solve 3/4 - 2/5, 5/6 + 1/4, and 2 1/3 + 1 5/6.",
            "Complete twelve unlike-denominator problems and simplify answers.",
            "Solve 2/3 + 3/5.",
            "19/15 = 1 4/15.",
        ),
        (
            "Multiply Fractions",
            "Multiply fractions and mixed numbers using area models and simplification.",
            "Shade 2/3 of 3/4 on a rectangle to show 6/12 = 1/2.",
            "Solve 4/5 x 2/3, 1 1/2 x 2/5, and 3 x 5/8.",
            "Complete ten fraction multiplication problems, including mixed numbers.",
            "Solve 3/4 x 2/5.",
            "6/20 = 3/10.",
        ),
        (
            "Divide Unit Fractions and Whole Numbers",
            "Interpret division involving unit fractions and whole numbers.",
            "Use fraction strips to show 3 / 1/4 as how many fourths are in 3 wholes.",
            "Model 1/3 / 4, 5 / 1/2, and 1/6 / 2 with drawings.",
            "Solve eight unit-fraction division problems and write a story for two.",
            "Solve 4 / 1/8.",
            "32.",
        ),
        (
            "Decimal Addition and Subtraction",
            "Add and subtract decimals to hundredths and thousandths.",
            "Line up decimal points for 12.4 + 3.86 and explain placeholder zeros.",
            "Solve 8.75 - 2.391, 16.08 + 4.927, and 30 - 7.46.",
            "Complete twelve decimal addition/subtraction problems and estimate each result.",
            "Solve 14.2 - 5.67.",
            "8.53.",
        ),
        (
            "Decimal Multiplication and Division",
            "Multiply and divide decimals using place-value reasoning.",
            "Estimate 3.2 x 1.4, multiply 32 x 14, then place the decimal using hundredths.",
            "Solve 4.5 x 2.6, 7.2 / 0.9, and 12.48 / 3.",
            "Complete ten decimal multiplication/division problems with estimate checks.",
            "Solve 2.4 x 0.3.",
            "0.72.",
        ),
        (
            "Volume of Rectangular Prisms",
            "Find volume using unit cubes and formulas V = l x w x h and V = B x h.",
            "Build a 3 by 4 by 2 prism with cubes and count layers.",
            "Calculate volumes for 5 x 6 x 2, 8 x 3 x 4, and a prism with base area 24 and height 7.",
            "Solve eight volume problems and draw one composite rectangular prism.",
            "Find volume of a 9 by 4 by 3 prism.",
            "108 cubic units.",
        ),
        (
            "Coordinate Plane",
            "Graph ordered pairs in the first quadrant and interpret coordinate patterns.",
            "Draw axes, label x before y, and plot (2, 5), (6, 1), and (0, 4).",
            "Plot a path from a table of ordered pairs and describe horizontal/vertical changes.",
            "Graph ten points and write coordinates for five plotted points.",
            "Which coordinate tells how far right: x or y?",
            "x-coordinate.",
        ),
        (
            "Numerical Expressions and Order of Operations",
            "Write, interpret, and evaluate numerical expressions with grouping symbols.",
            "Compare 6 + 4 x 3 with (6 + 4) x 3 using order of operations.",
            "Evaluate 18 - (5 + 3), 4 x (7 + 2), and 36 / 6 + 8.",
            "Write expressions for six word phrases and evaluate eight expressions.",
            "Evaluate 5 x (8 - 3) + 6.",
            "31.",
        ),
        (
            "Measurement Data and Line Plots With Fractions",
            "Use line plots to solve fraction addition and subtraction problems.",
            "Plot plant heights measured to the nearest eighth inch and combine repeated values.",
            "Find the total length of objects at 2 1/4, 2 1/4, and 3 1/8 inches.",
            "Create a line plot from fractional measurements and answer five operation questions.",
            "What is 2 1/4 + 2 1/4?",
            "4 1/2.",
        ),
        (
            "Classifying Two-Dimensional Figures",
            "Classify triangles and quadrilaterals by properties.",
            "Build a hierarchy showing squares as rectangles and rhombuses, and rectangles as parallelograms.",
            "Sort shapes by parallel sides, equal sides, right angles, and symmetry.",
            "Classify twelve shapes and write one property-based explanation for each group.",
            "Is every square a rectangle?",
            "Yes, because every square has four right angles and opposite sides parallel.",
        ),
    ]
    return _build_lessons(specs, "place-value charts, decimal grids, fraction strips, grid paper, centimeter cubes, rulers")


def _build_lessons(specs: list[tuple[str, str, str, str, str, str, str]], materials: str) -> list[dict[str, Any]]:
    lessons: list[dict[str, Any]] = []
    for index, (title, overview, model, guided, independent, assessment, answer_key) in enumerate(specs, start=1):
        lessons.append(
            _lesson(
                sequence_order=index,
                title=title,
                overview=overview,
                objective=overview,
                model=model,
                guided=guided,
                independent=independent,
                assessment=assessment,
                answer_key=answer_key,
                materials=materials,
                extension="Add a challenge problem that asks the student to explain the same idea with a new number set or a real-life scenario.",
                remediation="Return to concrete models, reduce the numbers, solve one example together, then have the student complete a parallel problem independently.",
            )
        )
    return lessons


_MATH_COURSES: list[BuiltInCourse] = [
    {
        "grade_level": 1,
        "title": "Grade 1 Math Foundations",
        "description": "A complete first grade sequence for number sense, addition, subtraction, measurement, time, geometry, fractions, and data.",
        "color": "#20d3ff",
        "icon": "abacus",
        "topics": ["counting to 120", "place value", "addition", "subtraction", "measurement", "time", "geometry", "fractions", "data"],
        "lessons": _grade_1_lessons(),
    },
    {
        "grade_level": 2,
        "title": "Grade 2 Math Foundations",
        "description": "A second grade sequence for fluency within 100, three-digit place value, money, time, measurement, arrays, and graphing.",
        "color": "#7c83ff",
        "icon": "calculator",
        "topics": ["skip counting", "three-digit place value", "addition", "subtraction", "money", "time", "measurement", "arrays", "graphs"],
        "lessons": _grade_2_lessons(),
    },
    {
        "grade_level": 3,
        "title": "Grade 3 Math Foundations",
        "description": "A third grade course for multiplication, division, properties, word problems, fractions, area, perimeter, elapsed time, and data.",
        "color": "#ff4f9e",
        "icon": "times",
        "topics": ["multiplication facts", "division", "fractions", "area", "perimeter", "elapsed time", "line plots"],
        "lessons": _grade_3_lessons(),
    },
    {
        "grade_level": 4,
        "title": "Grade 4 Math Foundations",
        "description": "A fourth grade course for multi-digit operations, factors, fractions, decimals, measurement conversion, and geometry.",
        "color": "#34d399",
        "icon": "division",
        "topics": ["place value", "multi-digit operations", "factors", "fractions", "decimals", "measurement", "angles", "symmetry"],
        "lessons": _grade_4_lessons(),
    },
    {
        "grade_level": 5,
        "title": "Grade 5 Math Foundations",
        "description": "A fifth grade bridge to middle school math with decimals, fraction operations, volume, coordinate planes, expressions, and geometry.",
        "color": "#fbbf24",
        "icon": "sigma",
        "topics": ["decimals", "powers of ten", "multi-digit operations", "fractions", "volume", "coordinate plane", "expressions", "geometry"],
        "lessons": _grade_5_lessons(),
    },
]


def list_builtin_math_courses() -> list[BuiltInCourse]:
    return deepcopy(_MATH_COURSES)


def get_builtin_math_course(grade_level: int) -> BuiltInCourse | None:
    for course in _MATH_COURSES:
        if course["grade_level"] == grade_level:
            return deepcopy(course)
    return None
