import { describe, expect, it } from 'vitest';
import * as helpers from './payload';
import { recipe } from '../../../screens/recipes/fixtures';
import type { CreateRecipeRequest } from '@family-manager/family-api/models';
const h = helpers as unknown as { payloadFromRecipe: (r: typeof recipe) => CreateRecipeRequest; preparePayload: (p: CreateRecipeRequest, id?: number) => CreateRecipeRequest; parseBackup: (s: string) => CreateRecipeRequest[]; removeIngredient: (p: CreateRecipeRequest, index: number) => CreateRecipeRequest; emptyPayload: () => CreateRecipeRequest };
describe('native recipe payload semantics', () => {
  it('preserves all editable fields but strips database-only fields', () => { const p = h.payloadFromRecipe(recipe); expect(p).toMatchObject({ servings: 4, yield_quantity: 2, yield_unit: 'liters', photo_url: recipe.photo_url, category_ids: [3], tag_ids: [5] }); expect(p).not.toHaveProperty('id'); expect(p.ingredients?.[0]).not.toHaveProperty('id'); expect(p.steps?.[0].ingredient_position_refs).toEqual([1]); });
  it('remaps stable positions when blank ingredients are omitted without linking another item', () => { const p = h.preparePayload({ title: ' Soup ', ingredients: [{ position: 1, item: '' }, { position: 2, item: 'water' }], steps: [{ position: 1, instruction: 'Boil', ingredient_position_refs: [1, 2, 2, 99] }] }); expect(p.title).toBe('Soup'); expect(p.steps?.[0].ingredient_position_refs).toEqual([1]); });
  it('removal remaps links and never silently reassigns deleted ingredients', () => { const p = h.removeIngredient(h.payloadFromRecipe(recipe), 0); expect(p.ingredients?.[0].item).toBe('herbs'); expect(p.steps?.map(s => s.ingredient_position_refs)).toEqual([[], [1]]); });
  it('does not invent step links on an unchanged edit', () => { const p = h.preparePayload({ ...h.payloadFromRecipe(recipe), steps: [{ position: 1, instruction: 'Rest', ingredient_position_refs: [] }] }, 11); expect(p.steps?.[0].ingredient_position_refs).toEqual([]); });
  it('rejects self components on save', () => { const p = h.preparePayload({ title: 'x', components: [{ component_recipe_id: 11 }, { component_recipe_id: 12 }] }, 11); expect(p.components).toEqual([{ component_recipe_id: 12 }]); });
  it('restore clears owner/category/tag/component/core database identities', () => { const rows = h.parseBackup(JSON.stringify({ version: 1, recipes: [{ ...recipe, parent_recipe_id: 999 }] })); expect(rows[0]).toMatchObject({ parent_recipe_id: null, category_ids: [], tag_ids: [], components: [] }); expect(rows[0]).not.toHaveProperty('owner_user_id'); });
  it.each(['null', '{}', '{"version":99,"recipes":[]}', '{"version":1,"recipes":[{}]}', '{"version":1,"recipes":[{"title":"x","ingredients":null}]}'])('rejects malformed or unsupported backup %s', value => { expect(() => h.parseBackup(value)).toThrow(/Unsupported or invalid recipe backup/); });
  it('initial form explicitly includes serving yield notes and one editable ingredient and step', () => { expect(h.emptyPayload()).toMatchObject({ servings: null, yield_quantity: null, yield_unit: '', notes: '', ingredients: [{ position: 1, item: '' }], steps: [{ position: 1, instruction: '', ingredient_position_refs: [] }] }); });
});
